### ISSUE TITLE
Pourquoi MySQL et pas juste SQL ?

### ISSUE THREAD

**Issue by Alex-D** [Grafikart/dev-map#1]
Il y a un amalgame entre MySQL et SQL je trouve :/ 

En l'état, ça empêche d'intégrer d'autres SGBDR au même niveau : MySQL, MariaDB, PostgreSQL, Oracle, SQLite, SQL Server, ...

**Comment by MobElian** [comment]
Pourquoi pas intégrer SQL (language).
Et ensuite, MySQL, MariaDB, PostgreSQL, etc.. (tool) qui eux auront SQL comme technologie requise?
