### ISSUE TITLE
Proposition: améliorer le contenu à partir de la Dev-Roadmap

### ISSUE THREAD

**Issue by Pierstoval** [Grafikart/dev-map#3]
Il existe une roadmap déjà très utilisée : https://github.com/kamranahmedse/developer-roadmap

L'idée serait de changer les sources de données et de s'adapter à cette roadmap régulièrement mise à jour.

**Comment by Grafikart** [comment]
L'objectif est un peu différent du coup je ne suis pas sûr que la developer roadmap soit adapté dans ce cas. L'idée est plutôt ici de définir les relation entre les languages / technos plutôt que d'avoir une opinion sur l'ordre d'apprentissage

**Comment by Pierstoval** [comment]
Sur quels critères te bases-tu pour déterminer des relations entre les langages ? Parce que théoriquement, Algorithmie ça s'applique à 100% des langages, allant du procédural au prototype en passant par le fonctionnel et l'objet... Etc.

**Comment by Grafikart** [comment]
Cela ne s'applique pas aux langages de structure (HTML / CSS) et je ne l'applique pas non plus au SQL. Mais autrement oui, il va être comme source de beaucoup de chemin ce n'est pas génant.
